---
title: "Discriminção de Genero"
author: "Rafael Ribeiro"
date: "13 de fevereiro de 2018"
output: html_document
---
# INTRODUÇÃO
## INTRODUÇÃO
### INTRODUÇÃO

O fato de a *diferença* salarial entre os sexos existir é nítido e comprovado em diversos estudos realizados na área econômica. Mulheres com o mesmo nível de escolaridade, cargo e experiência recebem menor remuneração salarial que homens, sendo que isso ocorre de forma persistente em vários países e setores industriais. O tema central deste estudo é medir o impacto desta discriminação no crescimento econômico dos municípios, ou seja, se a discriminação salarial entre homens e mulheres pode implicar em impactos positivos ou negativos na economia dos municípios brasileiros.

```{r}
hist(rnorm(30))
```

### METODOLOGIA

Aplicando metodologias econométricas em dados extraídos da Relação Anual de Informações Sociais (RAIS), dos períodos de 2007 e 2014, obteve-se o resultado de que a discriminação salarial tem efeito negativo no PIB per capita. Este efeito é significativo e controlado por diversos indicadores que medem o nível socioeconômico de cada município. Ou seja, no cenário brasileiro, comparando municípios com os mesmos níveis socioeconômicos, aqueles com menores indicadores de discriminação salarial apresentam um maior crescimento do PIB per capita no período estudado. 


### RESULTADOS

Este estudo pode ter uma importante aplicação política, argumentando que a igualdade de renda de gênero deve ser uma prioridade maior para os formuladores de políticas, visando os benefícios tanto da equidade social como da eficiência econômica. Por fim, este estudo é apenas parte de um esforço universal que visa despertar e motivar a igualdade de direitos e condições entre homens e mulheres, enfatizando não apenas os benefícios para a economia, mas sim para a vida em sociedade. 

